
'use strict';
const KantoRuntime=window.YSRuntime;
(()=>{
 const stops=[['Pewter City',27,24],['Cerulean City',58,18],['Vermilion City',62,57],['Celadon City',43,42],['Fuchsia City',61,81],['Saffron City',61,37],['Cinnabar Island',24,84],['Viridian City',18,55],['Indigo Plateau',10,11]];
 const accents=['#b9a08a','#5fc8ff','#f5d54c','#78c66c','#d979b9','#d590ff','#ff765d','#d4a46b','#e9edf4'];
 const washes=['#5b4a3b','#164f68','#5b5420','#31583b','#58304b','#493660','#66352c','#59452d','#46515c'];
 const leaderFiles=['leader_brock_front_pic.png','leader_misty_front_pic.png','leader_lt_surge_front_pic.png','leader_erika_front_pic.png','leader_koga_front_pic.png','leader_sabrina_front_pic.png','leader_blaine_front_pic.png','leader_giovanni_front_pic.png'];
 let selectedStop=0;
 const state=i=>i<KantoRuntime.save.cupsCompleted||(i===8&&KantoRuntime.save.eliteCompleted)?'completed':i===KantoRuntime.save.cupsCompleted?'current':'locked';
 function moveAvatar(i){const a=document.getElementById('journey-avatar');if(!a)return;a.style.left=`${stops[i][1]}%`;a.style.top=`${stops[i][2]}%`;}
 function teamSprites(cup){const wrap=document.createElement('div');wrap.className='v50-team';cup.team.forEach(id=>{const im=document.createElement('img');im.className='v50-mon';im.src=assetUrl(SPECIES[id].sprite);im.alt=SPECIES[id].name;wrap.append(im)});return wrap}
 function services(panel,city,status,gymAction){if(status==='locked')return;const wrap=document.createElement('div');wrap.className='ui2-city-services';const label=document.createElement('p');label.className='ui2-service-label';label.textContent='CITY SERVICES';wrap.append(label);const actions=document.createElement('div');actions.className='ui2-service-actions';if(gymAction){const gym=document.createElement('button');gym.type='button';gym.className='primary-button ui2-gym-action';gym.innerHTML=gymAction.label;gym.onclick=gymAction.onClick;actions.append(gym)}const center=document.createElement('button');center.type='button';center.className='secondary-button ui2-center-action';center.innerHTML='✚ POKÉCENTER';center.onclick=()=>window.PokeCenter?.open?.();const mart=document.createElement('button');mart.type='button';mart.className='secondary-button ui2-mart-action';mart.innerHTML='▣ POKÉ MART';mart.onclick=()=>typeof showShop==='function'&&showShop();actions.append(center,mart);wrap.append(actions);const note=document.createElement('small');note.textContent=`Services available in ${city}.`;wrap.append(note);panel.append(wrap)}
 function inspect(i,focus=false){
   const status=state(i); if(status==='locked'&&focus){const b=KantoRuntime.element('kanto-markers').querySelector(`[data-stop="${i}"]`);b?.animate?.([{transform:'translate(-50%,-50%)'},{transform:'translate(-50%,-50%) scale(.9)'},{transform:'translate(-50%,-50%)'}],{duration:220});return}
   selectedStop=i; moveAvatar(i);
   for(const b of KantoRuntime.element('kanto-markers').querySelectorAll('.map-marker'))b.setAttribute('aria-pressed',String(+b.dataset.stop===i));
   const panel=KantoRuntime.element('map-stop');panel.replaceChildren();panel.style.setProperty('--gym-accent',accents[i]);panel.style.setProperty('--gym-wash',washes[i]);
   if(i<8){const cup=CUPS[i];const portrait=document.createElement('img');portrait.className='v50-leader';portrait.src=assetUrl(`./assets/journey-v50/${leaderFiles[i]}`);portrait.alt=cup.leader;panel.append(portrait);
     const text=document.createElement('div');const kick=document.createElement('p');kick.className='v50-gym-kicker';kick.textContent=`GYM ${i+1} · ${cup.badge} BADGE`;const h=document.createElement('h2');h.textContent=`${stops[i][0]} Gym`;const meta=document.createElement('div');meta.className='v50-gym-meta';[cup.leader,...cup.types,'ADVENTURE PARTY'].forEach(x=>{const s=document.createElement('span');s.className='v50-chip';s.textContent=x;meta.append(s)});const note=document.createElement('p');note.className='stop-note';note.textContent=status==='completed'?`${cup.leader} defeated. Replay this Gym whenever you want.`:status==='current'?`You've reached ${stops[i][0]}. Bring your current adventure party and enter the Gym.`:`Defeat the previous Gym to open this route.`;text.append(kick,h,meta,note,teamSprites(cup));panel.append(text);
     if(status!=='locked'){const gymAction={label:KantoRuntime.selectedIds.length?`${status==='completed'?'REPLAY':'CHALLENGE'} GYM <span>›</span>`:'BUILD PARTY <span>›</span>',onClick:()=>KantoRuntime.selectedIds.length?startCup(i):window.PartyTray?.open()};services(panel,stops[i][0],status,gymAction)}
   } else {const text=document.createElement('div');const kick=document.createElement('p');kick.className='v50-gym-kicker';kick.textContent='POKÉMON LEAGUE';const h=document.createElement('h2');h.textContent='Indigo Plateau';const note=document.createElement('p');note.className='stop-note';note.textContent=KantoRuntime.save.cupsCompleted===8?'All eight badges are yours. The Elite Four await.':'Earn all eight badges to unlock the League.';text.append(kick,h,note);panel.append(text);if(KantoRuntime.save.cupsCompleted===8){const btn=document.createElement('button');btn.type='button';btn.className='primary-button';btn.innerHTML='ENTER LEAGUE <span>›</span>';btn.onclick=()=>KantoRuntime.element('elite-panel').scrollIntoView({block:'center',behavior:'smooth'});panel.append(btn)}}
   if(focus)panel.scrollIntoView?.({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 }
 function render(){
   const mapArt=document.querySelector('#kanto-map img[data-demand-src]');
   if(mapArt) AssetDemand.assignImage(mapArt,mapArt.dataset.demandSrc,{priority:'high',loading:'eager'});
   AssetDemand.preloadGroup('journey-ui','low');
   KantoRuntime.element('badge-count').textContent=`${KantoRuntime.save.cupsCompleted} / 8`;KantoRuntime.element('cup-summary').textContent=KantoRuntime.save.cupsCompleted<8?`Next route: ${stops[KantoRuntime.save.cupsCompleted][0]} · ${CUPS[KantoRuntime.save.cupsCompleted].leader}`:KantoRuntime.save.eliteCompleted?'Kanto Champion — every Gym conquered.':'All eight badges earned. Indigo Plateau is open.';
   const holder=KantoRuntime.element('kanto-markers');holder.replaceChildren();document.querySelectorAll('.v50-city-label').forEach(x=>x.remove());
   stops.forEach(([city,x,y],i)=>{const st=state(i),b=document.createElement('button');b.type='button';b.className=`map-marker ${st}`;b.style.left=`${x}%`;b.style.top=`${y}%`;b.dataset.stop=i;b.setAttribute('aria-pressed','false');b.setAttribute('aria-label',`${city}. ${st}.`);if(st==='current')b.setAttribute('aria-current','step');if(i<8){const icon=document.createElement('span');icon.className='kanto-badge';window.TrainerScenes.badge(icon,i);b.append(icon)}else b.textContent='E4';b.onclick=()=>inspect(i,true);holder.append(b);if(st!=='locked'){const label=document.createElement('span');label.className=`v50-city-label ${st}`;label.style.left=`${x}%`;label.style.top=`${y}%`;label.textContent=i===8?'LEAGUE':city.replace(' City','').toUpperCase();document.getElementById('kanto-map').append(label)}});
   const svg=document.querySelector('.journey-route polyline');if(svg)svg.setAttribute('points',stops.map(s=>`${s[1]},${s[2]}`).join(' '));inspect(Math.min(KantoRuntime.save.cupsCompleted,8));renderElitePanel();
 }
 window.KantoMap={render,inspect,stops};
})();

